services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev            # utilise nodemon
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app                      # monte ton code
      - /app/node_modules           # évite d'écraser node_modules du conteneur
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 2s
      retries: 5
